config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  match "/", to: "paws_up#create", as: "paws_ups", via: :post
  match "/neglected", to: "pages#neglect", via: :get
  match "secret", to: "paws_up#index", via: :get
  match "secret", to: "paws_up#index", via: :post

  resources :cycles, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cycle.rb
class Cycle < ApplicationRecord
  has_many :paws_ups
end

app/models/paws_up.rb
# == Schema Information
#
# Table name: paws_ups
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  from_user_id :integer
#  description  :text
#  created_at   :datetime
#  updated_at   :datetime
#  custom_for   :string
#  value        :string
#

class PawsUp < ApplicationRecord
  validates :description, presence: true
  validate :has_user_id_or_custom_for
  belongs_to :cycle

  def has_user_id_or_custom_for
    if self.user_id.nil? && self.custom_for.empty?
      errors.add(:you, "must provide either a blooper or a custom group.")
    end
  end

  def recipient
    if user_id.nil?
      custom_for
    else
      User.find(user_id).name
    end
  end

  def to_s
    "Paws Up to #{recipient} for #{description}" + value_string
  end

  private

  def value_string
    if value
      " (#{value})"
    else
      ""
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  created_at :datetime
#  updated_at :datetime
#

class User < ApplicationRecord
  has_many :paws_ups
end

app/models/values.rb
class Values
  def self.names
    ["Mission First", "Perpetual Growth", "Cherish Each Other", "Always Innovate", "Be Humble"]
  end

  def self.descriptions
    ["We as Blueprint members ultimately unify under one goal - achieving our mission. We place the interests of the people and clients we serve above our own. Our primary measure of success is the amount of positive impact we create through our work.",
     "We as Blueprint members value the academic, social, and personal growth of our peers. We constantly seek to perpetuate the cycle of learning and teaching, for our benefit and for others’. We strive to offer a helping hand in times of need and push each other to succeed.",
     "We as Blueprint members seek to cherish our time spent together. We develop meaningful relationships that extend well beyond the scope of the organization. We value each other as individuals and appreciate our differences.",
     "We as Blueprint members recognize that change is both inevitable and necessary. We are committed to innovate and emphasize effective solutions as needed in order to remain relevant - nothing is sacred. We welcome new ideas and diverse thinking.",
     "We as Blueprint members strive to remain humble, accept our imperfections, and be receptive to feedback. We approach challenges with an open mind and remember that anyone can pursue social good, not just Blueprint."]
  end

  def self.collection
    self.names.zip self.names
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/cycle_controller.rb
class CycleController < ApplicationController

  def create
    Cycle.create
    redirect_to '/secret'
  end
end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController

  def create
    Cycle.create
    redirect_to '/secret'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @paws_up = PawsUp.new
  end

  def about
  end

  def neglect
    if params[:weeks].nil?
      redirect_to '/neglected?weeks=2'
    else
      @weeks = [params[:weeks].to_i, Cycle.count - 1].min
      cycle_ids = Cycle.all.reverse_order[0, @weeks + 1].map {|c| c.id}
      recipients = PawsUp.where(cycle_id: cycle_ids).map { |p| p.user_id}
      @neglected_bloopers = User.where.not(inactive: true, id: recipients)
    end
  end

end

app/controllers/paws_up_controller.rb
class PawsUpController < ApplicationController

  EMOJIS = ['😁', '🤯', '🥱', '😽', '💩', '🤪', '🌞', '🌝'].freeze

  def create
    if Cycle.count > 0
      @paws_up = Cycle.last.paws_ups.new(paws_up_params)
    else
      @paws_up = PawsUp.new(paws_up_params)
    end

    if @paws_up.save
      flash[:success] = "Successfully sent your Paws Up!"
      redirect_to root_path
    else
      flash[:danger] = "There was a problem sending your Paws Up, please try again."
      redirect_to root_path
    end
  end

  def index
    if params[:secret].nil? || params[:secret] == ENV["secret"]

      @current_paws_up = PawsUp.where(cycle: Cycle.last).order(created_at: :desc)
      @previous_cycles = Cycle.where.not(id: Cycle.last.id).reverse_order
      @emoji = EMOJIS.sample
      # @previous_paws_up = PawsUp.where.not(cycle: Cycle.last).order(created_at: :desc)
      if params[:random] != "false"
        @current_paws_up = @current_paws_up.shuffle
      end
    else
      flash[:danger] = "You are not allowed to view this page."
      redirect_to root_path
    end
  end

  private

  def paws_up_params
    params.require(:paws_up).permit(:user_id, :description, :custom_for, :value)
  end

end

app/controllers/paws_ups_controller.rb
class PawsUpsController < ApplicationController

  def create
    @paws_up = PawsUp.new(paws_up_params)
    if @paws_up.save
      redirect_to root_path, success: "Successfully sent Paws Up!"
    else
      redirect_to root_path, error: "There was a problem sending your Paws Up, please try again."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_li_link(name=nil, options={}, html_options={}, link_html_options={}, &block)
    html_options[:class] = "#{html_options[:class]} active" if current_page?(options)
    content_tag :li, html_options do
      link_to(name, options, link_html_options)
    end
  end

end

app/views/layouts/_footer.html.slim
.footer
  p.text-heading-white.center
    | Made with lots of <3 and caffeine by Blueprint &copy; 2021

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-fixed-top role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target="collapsed-navbar"
        span.sr-only Toggle Navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Paws Up", root_path, class: "navbar-brand"
    .collapse.navbar-collapse#collapsed-navbar
      ul.nav.navbar-nav#header-links
        - if content_for?(:header_links)
          = render partial: yield(:header_links)

app/views/layouts/application.html.slim
doctype html

html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title = content_for?(:title) ? yield(:title) : "Paws Up!"
    link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700"
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true, "modernizr" => true
    = csrf_meta_tags

  body
    = yield
    = render partial: "layouts/footer"

app/views/pages/home.html.slim
= provide(:header_links, "header/home")

.main
  section#intro
    .container
      .row
        .col-md-12.center
          .about-intro
            h1.white
              ' Paws Up to Blueprint
              span#typer
  section#form
    .container
      .row
        .col-md-8.col-md-offset-2
          .paws-up-to-container.center
            = render partial: "shared/form_errors", locals: {errors: @paws_up.errors}
            = render partial: "shared/errors"
            h1 Who do you want to send Paws Up to?
            = simple_form_for @paws_up do |f|
              = f.collection_select :user_id, User.where(inactive: false).order(:name), :id, :name, {prompt: "Select a blueper"}, class: "form-control medium center"
              = f.input :custom_for, input_html: {class: "form-control medium"}, label: "Or for a group of bluepers:", label_html: {class: "large-question"}
              = f.input :description, as: :text, input_html: {class: "form-control medium"}, label: "What are you giving it for?", label_html: {class: "large-question"}
              = f.input :value, collection: Values.collection, input_html: {class: "form-control medium"}, label: "What value does it represent?", label_html: {class: "large-question"}
              = f.button :submit, "Give Paws Up!", class: "flat-button"

app/views/pages/neglect.html.slim
h1 = "People who haven't gotten a paws up in the last #{@weeks} cycles"
h3 This does not include paws up given to "groups" of people. If you think you gave a paws up to someone but are unsure, just ask someone on eteam! 
- @neglected_bloopers.each do |blooper|
    = blooper.name
    p 

app/views/paws_up/index.html.slim
.main
  .container
    .row
      .col-md-12
        - if params[:secret] == ENV["secret"]
          = button_to "Create New Paws Up Cycle", cycles_path, class: "flat-button"
          .this-week-container
            h1 Paws Up From This Week
            p = "There are #{@current_paws_up.count} paws up this week. Good luck Elizabeth! #{@emoji}"
            - @current_paws_up.each do |paws_up|
              .paws_up
                = paws_up
          .previous-container
            h1 Paws Up From Previous Weeks
            - @previous_cycles.each do |cycle|
              - PawsUp.where(cycle: cycle).each do |paws_up|
                .paws_up
                  = paws_up
              br
              br
        - else
          .secret-text-box
            = form_tag "secret", method: :post do |f|
              = password_field_tag :secret, params[:secret], class: "form-control small-form"
              .submit-button
                = submit_tag "Enter", class: "flat-button"

app/views/shared/_errors.html.slim
.row
  .col-md-12.center
    - flash.each do |key, value|
      div class="alert alert-#{key}"
        = value

app/views/shared/_form_errors.html.slim
- if errors.any?
  .container
    .row
      .col-md-12
        .alert.alert-danger#error-explanation
          h2.error-heading
            = pluralize(errors.count, "error")
            | prohibited this form from being saved:
          ul
            - errors.full_messages.each do |message|
              li = message